[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding.y = 16
padding.x = 16
opacity = 0.8

[font]
size = 11.6

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Bold"
