[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding.y = 16
padding.x = 16
opacity = 1

[font]
size = 15.6

[font.normal]
family = "Iosevka Nerd Font"
# family = "Mx437 IBM VGA 8x16"
style = "SemiBold"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"
