[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
# padding.y = 0
# padding.x = 0
padding.y = 4
padding.x = 4
opacity = 0.8

[font]
size = 11.6

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"
